---
- hosts: all
  become: yes

  roles:
        #
        # Basics
        #
        - role: system
          tags:
              - system
        - name: containers
          tags:
            - containers
        - role: geerlingguy.docker
          tags:
              - docker
        - role: geerlingguy.pip